# Generated by Django 5.2.6 on 2025-09-28 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('type_contact', models.CharField(choices=[('informacao', "Demande d'information"), ('devis', 'Demande de devis'), ('reclamation', 'Réclamation'), ('autre', 'Autre')], default='informacao', max_length=20, verbose_name='Type de contact')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('adresse_projet', models.CharField(blank=True, max_length=255, verbose_name='Adresse du projet')),
                ('ville_projet', models.CharField(blank=True, max_length=100, verbose_name='Ville du projet')),
                ('surface_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface estimée (m²)')),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget estimé (€)')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('ferme', 'Fermé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('notes_internes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='contatos/pieces_jointes/', verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom original')),
                ('taille', models.PositiveIntegerField(verbose_name='Taille (bytes)')),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contato.contato', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-date_upload'],
            },
        ),
    ]
