# Generated by Django 5.2.6 on 2025-10-12 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('type_projet', models.CharField(choices=[('interieur', 'Peinture Intérieure'), ('exterieur', 'Peinture Extérieure'), ('renovation', 'Rénovation'), ('decoration', 'Décoration')], max_length=20, verbose_name='Type de projet')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface (m²)')),
                ('prix_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix estimé (€)')),
                ('image_principale', models.ImageField(blank=True, upload_to='projetos/', verbose_name='Image principale')),
                ('visible_site', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projetos/galeria/')),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Image du projet',
                'verbose_name_plural': 'Images du projet',
                'ordering': ['ordre'],
            },
        ),
    ]
