# Generated by Django 5.2.6 on 2025-10-14 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEntrepreneurParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_product_type', models.CharField(choices=[('marchandise', 'Fourniture / Marchandise'), ('service', 'Service')], default='service', max_length=20)),
                ('declaration_periodicite', models.CharField(choices=[('mois', 'Mois'), ('trimestre', 'Trimestre')], default='trimestre', max_length=15)),
                ('biens_taux_cotisation_sociale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('biens_taux_imposition', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('biens_taux_formation_pro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('biens_taux_chambre_consulaire', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('services_taux_cotisation_sociale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('services_taux_imposition', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('services_taux_formation_pro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('services_taux_chambre_consulaire', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Auto-Entrepreneur',
                'verbose_name_plural': 'Paramètres Auto-Entrepreneur',
            },
        ),
        migrations.CreateModel(
            name='Civilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('abreviation', models.CharField(blank=True, max_length=10)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Civilité',
                'verbose_name_plural': 'Civilités',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=100)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('actif', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Email',
                'verbose_name_plural': 'Paramètres Email',
            },
        ),
        migrations.CreateModel(
            name='InterfaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='interface/logo/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='interface/background/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètres d'interface",
                'verbose_name_plural': "Paramètres d'interface",
            },
        ),
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Forme juridique')),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forme juridique',
                'verbose_name_plural': 'Formes juridiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condition de paiement',
                'verbose_name_plural': 'Conditions de paiement',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Mode de règlement')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mode de règlement',
                'verbose_name_plural': 'Modes de règlement',
                'ordering': ['ordre', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_type', models.CharField(choices=[('tva', 'TVA'), ('autre', 'Autre')], default='tva', max_length=10)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taux de taxe',
                'verbose_name_plural': 'Taux de taxes',
                'ordering': ['tax_type', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, default='France', max_length=80)),
                ('siret', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9 ]*$', 'SIRET invalide')])),
                ('code_ape', models.CharField(blank=True, max_length=10)),
                ('code_rcs', models.CharField(blank=True, max_length=50)),
                ('tva_intra', models.CharField(blank=True, max_length=30)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_internet', models.URLField(blank=True)),
                ('activite', models.CharField(blank=True, max_length=150)),
                ('type_entreprise', models.CharField(blank=True, help_text='Auto entrepreneur / micro entreprise / autre', max_length=40)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('responsable_nom', models.CharField(blank=True, max_length=80)),
                ('responsable_prenom', models.CharField(blank=True, max_length=80)),
                ('expert_raison_sociale', models.CharField(blank=True, max_length=150)),
                ('expert_adresse', models.CharField(blank=True, max_length=255)),
                ('expert_code_postal', models.CharField(blank=True, max_length=10)),
                ('expert_ville', models.CharField(blank=True, max_length=100)),
                ('expert_nom_prenom', models.CharField(blank=True, max_length=150)),
                ('expert_tel', models.CharField(blank=True, max_length=20)),
                ('expert_mobile', models.CharField(blank=True, max_length=20)),
                ('expert_fax', models.CharField(blank=True, max_length=20)),
                ('expert_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_civilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='system_config.civilite')),
                ('forme_juridique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_config.legalform')),
            ],
            options={
                'verbose_name': 'Paramètres Société',
                'verbose_name_plural': 'Paramètres Société',
            },
        ),
    ]
