# Generated by Django 5.2.6 on 2025-09-28 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur (hex)')),
                ('actif', models.BooleanField(default=True, verbose_name='Catégorie active')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de blog',
                'verbose_name_plural': 'Catégories de blog',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Lista')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('active', models.BooleanField(default=True, verbose_name='Lista Ativa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Lista de Newsletter',
                'verbose_name_plural': 'Listas de Newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('resume', models.TextField(max_length=300, verbose_name='Résumé/Extrait')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('tags', models.CharField(blank=True, help_text='Séparez les tags par des virgules', max_length=200, verbose_name='Tags')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/articles/', verbose_name='Image principale')),
                ('text_alt', models.CharField(blank=True, max_length=200, verbose_name="Texte alternatif de l'image")),
                ('temps_lecture', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Meta keywords')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('featured', models.BooleanField(default=False, verbose_name='Article en vedette')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categorieblog', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Date de modération')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blog.articleblog', verbose_name='Article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='blog.commentaireblog', verbose_name='Réponse à')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('interests', models.CharField(blank=True, max_length=255, verbose_name="Centres d'intérêt")),
                ('rgpd_consent', models.BooleanField(default=False, verbose_name='Consentement RGPD')),
                ('active', models.BooleanField(default=True, verbose_name='Assinante Ativo')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Email Confirmé')),
                ('confirmation_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de Confirmação')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Date de Confirmation')),
                ('last_email_sent', models.DateTimeField(blank=True, null=True, verbose_name='Dernier Email Envoyé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('lists', models.ManyToManyField(blank=True, related_name='subscribers', to='blog.newsletterlist', verbose_name='Listas')),
            ],
            options={
                'verbose_name': 'Assinante de Newsletter',
                'verbose_name_plural': 'Assinantes de Newsletter',
                'ordering': ['-date_joined'],
            },
        ),
    ]
