# Generated by Django 5.2.6 on 2025-09-28 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icone', models.CharField(default='fas fa-palette', help_text='Classe CSS do ícone FontAwesome', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Couleur',
                'verbose_name_plural': 'Catégories de Couleurs',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(help_text='Code unique de la couleur (ex: RAL-1000)', max_length=50, unique=True)),
                ('rgb_r', models.PositiveIntegerField(help_text='Rouge (0-255)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('rgb_g', models.PositiveIntegerField(help_text='Vert (0-255)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('rgb_b', models.PositiveIntegerField(help_text='Bleu (0-255)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('hex_color', models.CharField(blank=True, help_text='Couleur en format HEX (calculé automatiquement)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Description de la couleur')),
                ('disponible', models.BooleanField(default=True)),
                ('populaire', models.BooleanField(default=False, help_text='Couleur populaire/recommandée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couleurs', to='home.categoriacolor')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['categoria__ordem', 'categoria__nome', 'nome'],
                'unique_together': {('nome', 'categoria')},
            },
        ),
    ]
