# Generated by Django 5.2.6 on 2025-10-12 16:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Client')),
                ('civilite', models.CharField(blank=True, choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('MLLE', 'Mademoiselle'), ('DR', 'Docteur'), ('PROF', 'Professeur')], max_length=10, verbose_name='Civilité')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison Sociale')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[+]?[0-9\\s\\-\\(\\)\\.]{8,20}$')], verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[+]?[0-9\\s\\-\\(\\)\\.]{8,20}$')], verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('url', models.URLField(blank=True, verbose_name='Site Web')),
                ('activite', models.CharField(blank=True, max_length=200, verbose_name='Activité')),
                ('siret', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Le SIRET doit contenir 14 chiffres', regex='^\\d{14}$')], verbose_name='SIRET')),
                ('code_ape', models.CharField(blank=True, max_length=10, verbose_name='Code APE')),
                ('tva_intra', models.CharField(blank=True, choices=[('', 'Non applicable'), ('FR', 'France - FR'), ('BE', 'Belgique - BE'), ('DE', 'Allemagne - DE'), ('ES', 'Espagne - ES'), ('IT', 'Italie - IT'), ('LU', 'Luxembourg - LU'), ('NL', 'Pays-Bas - NL'), ('PT', 'Portugal - PT'), ('AT', 'Autriche - AT'), ('CH', 'Suisse - CH'), ('GB', 'Royaume-Uni - GB'), ('IE', 'Irlande - IE'), ('DK', 'Danemark - DK'), ('SE', 'Suède - SE'), ('FI', 'Finlande - FI'), ('NO', 'Norvège - NO'), ('PL', 'Pologne - PL'), ('CZ', 'République tchèque - CZ'), ('HU', 'Hongrie - HU'), ('autre', 'Autre (saisie libre)')], max_length=20, verbose_name='TVA Intracommunautaire')),
                ('tva_intra_custom', models.CharField(blank=True, help_text="Utilisé quand 'Autre' est sélectionné", max_length=50, verbose_name='TVA Intracommunautaire (saisie libre)')),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client')], default='prospect', max_length=20, verbose_name='Statut')),
                ('origem', models.CharField(choices=[('dashboard', 'Criado via Dashboard'), ('auto_registro', 'Auto-registro (Login)'), ('devis_publico', 'Solicitação de Devis Público')], default='dashboard', max_length=20, verbose_name='Origem')),
                ('taux_tva_defaut', models.CharField(choices=[('20', 'TVA 20%'), ('10', 'TVA 10%'), ('5.5', 'TVA 5,5%'), ('0', 'Exonérée')], default='20', max_length=10, verbose_name='Taux TVA par défaut (%)')),
                ('remise_globale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise globale (%)')),
                ('conditions_paiement', models.CharField(choices=[('30_acompte_solde_fin', "30% d'acompte à la commande, le solde fin du chantier"), ('paiement_fin_mois', 'Paiement la fin du mois'), ('paiement_30j_fin_mois', 'Paiement 30 jours fin du mois')], default='30_acompte_solde_fin', max_length=50, verbose_name='Conditions de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Associado')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['origem', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='AdresseTransporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'adresse")),
                ('copier_adresse_principale', models.BooleanField(default=False, verbose_name="Copier l'adresse principale")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default='France', max_length=100, verbose_name='Pays')),
                ('contact_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du contact')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_transporteur', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Adresse Transporteur',
                'verbose_name_plural': 'Adresses Transporteur',
            },
        ),
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'adresse")),
                ('copier_adresse_principale', models.BooleanField(default=False, verbose_name="Copier l'adresse principale")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default='France', max_length=100, verbose_name='Pays')),
                ('contact_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_livraison', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
            },
        ),
        migrations.CreateModel(
            name='AdresseChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du chantier')),
                ('copier_adresse_principale', models.BooleanField(default=False, verbose_name="Copier l'adresse principale")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default='France', max_length=100, verbose_name='Pays')),
                ('responsable_nom', models.CharField(blank=True, max_length=100, verbose_name='Responsable du chantier')),
                ('responsable_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du responsable')),
                ('instructions_acces', models.TextField(blank=True, verbose_name="Instructions d'accès")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_chantier', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Adresse Chantier',
                'verbose_name_plural': 'Adresses Chantier',
            },
        ),
        migrations.CreateModel(
            name='TarifTVAClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux TVA (%)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_tva', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Tarif TVA Client',
                'verbose_name_plural': 'Tarifs TVA Client',
                'unique_together': {('client', 'taux_tva')},
            },
        ),
    ]
