# Generated by Django 5.2.6 on 2025-10-01 21:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Client')),
                ('civilite', models.CharField(blank=True, choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('MLLE', 'Mademoiselle'), ('DR', 'Docteur'), ('PROF', 'Professeur')], max_length=10, verbose_name='Civilité')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison Sociale')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[+]?[0-9\\s\\-\\(\\)\\.]{8,20}$')], verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[+]?[0-9\\s\\-\\(\\)\\.]{8,20}$')], verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('url', models.URLField(blank=True, verbose_name='Site Web')),
                ('activite', models.CharField(blank=True, max_length=200, verbose_name='Activité')),
                ('siret', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Le SIRET doit contenir 14 chiffres', regex='^\\d{14}$')], verbose_name='SIRET')),
                ('code_ape', models.CharField(blank=True, max_length=10, verbose_name='Code APE')),
                ('tva_intra', models.CharField(blank=True, max_length=20, verbose_name='TVA Intracommunautaire')),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client')], default='prospect', max_length=20, verbose_name='Statut')),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux TVA par défaut (%)')),
                ('remise_globale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise globale (%)')),
                ('conditions_paiement', models.CharField(choices=[('30_acompte_solde_fin', "30% d'acompte à la commande, le solde fin du chantier"), ('paiement_fin_mois', 'Paiement la fin du mois'), ('paiement_30j_fin_mois', 'Paiement 30 jours fin du mois')], default='30_acompte_solde_fin', max_length=50, verbose_name='Conditions de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='AdresseTransporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du transporteur')),
                ('copier_adresse_principale', models.BooleanField(default=False, verbose_name="Copier l'adresse principale")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('contact_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_transporteur', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Adresse transporteur',
                'verbose_name_plural': 'Adresses transporteur',
            },
        ),
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'adresse")),
                ('copier_adresse_principale', models.BooleanField(default=False, verbose_name="Copier l'adresse principale")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('contact_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_livraison', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
            },
        ),
        migrations.CreateModel(
            name='AdresseChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du chantier')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('contact_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du contact sur site')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Date début prévue')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date fin prévue')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_chantier', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Adresse de chantier',
                'verbose_name_plural': 'Adresses de chantier',
            },
        ),
        migrations.CreateModel(
            name='TarifTVAClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux TVA (%)')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='Taux par défaut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_tva', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Tarif TVA',
                'verbose_name_plural': 'Tarifs TVA',
                'unique_together': {('client', 'description')},
            },
        ),
    ]
