# Generated by Django 5.2.6 on 2025-10-01 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['origem', 'nom', 'prenom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem',
            field=models.CharField(choices=[('dashboard', 'Criado via Dashboard'), ('auto_registro', 'Auto-registro (Login)'), ('devis_publico', 'Solicitação de Devis Público')], default='dashboard', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Associado'),
        ),
    ]
