# Generated by Django 5.2.6 on 2025-10-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_origem_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tva_intra_custom',
            field=models.CharField(blank=True, help_text="Utilisé quand 'Autre' est sélectionné", max_length=50, verbose_name='TVA Intracommunautaire (saisie libre)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tva_intra',
            field=models.CharField(blank=True, choices=[('', 'Non applicable'), ('FR', 'France - FR'), ('BE', 'Belgique - BE'), ('DE', 'Allemagne - DE'), ('ES', 'Espagne - ES'), ('IT', 'Italie - IT'), ('LU', 'Luxembourg - LU'), ('NL', 'Pays-Bas - NL'), ('PT', 'Portugal - PT'), ('AT', 'Autriche - AT'), ('CH', 'Suisse - CH'), ('GB', 'Royaume-Uni - GB'), ('IE', 'Irlande - IE'), ('DK', 'Danemark - DK'), ('SE', 'Suède - SE'), ('FI', 'Finlande - FI'), ('NO', 'Norvège - NO'), ('PL', 'Pologne - PL'), ('CZ', 'République tchèque - CZ'), ('HU', 'Hongrie - HU'), ('autre', 'Autre (saisie libre)')], max_length=20, verbose_name='TVA Intracommunautaire'),
        ),
    ]
