# Generated by Django 5.2.6 on 2025-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_tva_intra_custom_alter_cliente_tva_intra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='taux_tva_defaut',
            field=models.CharField(choices=[('20', 'TVA 20%'), ('10', 'TVA 10%'), ('5.5', 'TVA 5,5%'), ('0', 'Exonérée')], default='20', max_length=10, verbose_name='Taux TVA par défaut (%)'),
        ),
    ]
