# Generated by Django 5.2.6 on 2025-10-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_taux_tva_defaut'),
    ]

    operations = [
    ]
