# Generated by Django 5.2.6 on 2025-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20251005_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adressechantier',
            options={'verbose_name': 'Adresse Chantier', 'verbose_name_plural': 'Adresses Chantier'},
        ),
        migrations.AlterModelOptions(
            name='adressetransporteur',
            options={'verbose_name': 'Adresse Transporteur', 'verbose_name_plural': 'Adresses Transporteur'},
        ),
        migrations.AlterModelOptions(
            name='tariftvaclient',
            options={'verbose_name': 'Tarif TVA Client', 'verbose_name_plural': 'Tarifs TVA Client'},
        ),
        migrations.RemoveField(
            model_name='adressechantier',
            name='contact_nom',
        ),
        migrations.RemoveField(
            model_name='adressechantier',
            name='contact_telephone',
        ),
        migrations.RemoveField(
            model_name='adressechantier',
            name='date_debut_prevue',
        ),
        migrations.RemoveField(
            model_name='adressechantier',
            name='date_fin_prevue',
        ),
        migrations.RemoveField(
            model_name='adressechantier',
            name='instructions',
        ),
        migrations.AlterUniqueTogether(
            name='tariftvaclient',
            unique_together={('client', 'taux_tva')},
        ),
        migrations.AddField(
            model_name='adressechantier',
            name='copier_adresse_principale',
            field=models.BooleanField(default=False, verbose_name="Copier l'adresse principale"),
        ),
        migrations.AddField(
            model_name='adressechantier',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='adressechantier',
            name='instructions_acces',
            field=models.TextField(blank=True, verbose_name="Instructions d'accès"),
        ),
        migrations.AddField(
            model_name='adressechantier',
            name='responsable_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable du chantier'),
        ),
        migrations.AddField(
            model_name='adressechantier',
            name='responsable_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du responsable'),
        ),
        migrations.AddField(
            model_name='adressetransporteur',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='tariftvaclient',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='tariftvaclient',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='adressechantier',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='adressechantier',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='adressechantier',
            name='nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du chantier'),
        ),
        migrations.AlterField(
            model_name='adressechantier',
            name='pays',
            field=models.CharField(blank=True, default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='adressechantier',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='nom',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom de l'adresse"),
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='pays',
            field=models.CharField(blank=True, default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='adressetransporteur',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='adressetransporteur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='adressetransporteur',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du contact'),
        ),
        migrations.AlterField(
            model_name='adressetransporteur',
            name='contact_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du contact'),
        ),
        migrations.AlterField(
            model_name='adressetransporteur',
            name='nom',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom de l'adresse"),
        ),
        migrations.AlterField(
            model_name='adressetransporteur',
            name='pays',
            field=models.CharField(blank=True, default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='adressetransporteur',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='tariftvaclient',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tariftvaclient',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux TVA (%)'),
        ),
        migrations.RemoveField(
            model_name='tariftvaclient',
            name='par_defaut',
        ),
    ]
