# Generated by Django 5.2.6 on 2025-09-28 17:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titre du devis')),
                ('descricao', models.TextField(verbose_name='Description')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sous-total')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant de la remise')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('prazo_execucao', models.PositiveIntegerField(verbose_name="Délai d'exécution (jours)")),
                ('validade_orcamento', models.DateField(verbose_name='Validité du devis')),
                ('condicoes_pagamento', models.TextField(verbose_name='Conditions de paiement')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observations')),
                ('status', models.CharField(choices=[('pendente', 'En attente'), ('em_elaboracao', "En cours d'élaboration"), ('enviado', 'Envoyé au client'), ('aceito', 'Accepté'), ('recusado', 'Refusé'), ('expirado', 'Expiré')], default='em_elaboracao', max_length=20, verbose_name='Statut')),
                ('data_elaboracao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_resposta_cliente', models.DateTimeField(blank=True, null=True)),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_elaborados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-data_elaboracao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Description')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unidade', models.CharField(default='m²', max_length=20, verbose_name='Unité')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('total_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'Item do devis',
                'verbose_name_plural': 'Itens do devis',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('descricao', models.TextField(verbose_name='Description détaillée')),
                ('tipo_servico', models.CharField(choices=[('pintura_interior', 'Peinture intérieure'), ('pintura_exterior', 'Peinture extérieure'), ('renovacao_completa', 'Rénovation complète'), ('preparacao_superficies', 'Préparation des surfaces'), ('decoracao', 'Décoration'), ('reparos', 'Réparations'), ('outro', 'Autre')], max_length=50, verbose_name='Type de service')),
                ('urgencia', models.CharField(choices=[('baixa', 'Pas pressé'), ('media', 'Normal'), ('alta', 'Urgent'), ('critica', 'Très urgent')], default='media', max_length=20, verbose_name='Urgence')),
                ('endereco_projeto', models.CharField(max_length=255, verbose_name='Adresse du projet')),
                ('cidade_projeto', models.CharField(max_length=100, verbose_name='Ville')),
                ('cep_projeto', models.CharField(max_length=10, verbose_name='Code postal')),
                ('area_aproximada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface approximative (m²)')),
                ('numero_comodos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pièces')),
                ('altura_teto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hauteur du plafond (m)')),
                ('orcamento_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget estimé (€)')),
                ('data_inicio_desejada', models.DateField(blank=True, null=True, verbose_name='Date de début souhaitée')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observations particulières')),
                ('status', models.CharField(choices=[('planejando', 'En planification'), ('em_andamento', 'En cours'), ('concluido', 'Terminé'), ('pausado', 'En pause'), ('cancelado', 'Annulé')], default='planejando', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnexoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='projetos/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='orcamentos.projeto')),
            ],
            options={
                'verbose_name': 'Anexo do projeto',
                'verbose_name_plural': 'Anexos do projeto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_solicitante', models.CharField(max_length=100, verbose_name='Nom')),
                ('email_solicitante', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone_solicitante', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\+]?[0-9\\s\\-\\(\\)]+$')], verbose_name='Téléphone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Adresse')),
                ('cidade', models.CharField(max_length=100, verbose_name='Ville')),
                ('cep', models.CharField(max_length=10, verbose_name='Code postal')),
                ('tipo_servico', models.CharField(choices=[('pintura_interior', 'Peinture intérieure'), ('pintura_exterior', 'Peinture extérieure'), ('renovacao_completa', 'Rénovation complète'), ('preparacao_superficies', 'Préparation des surfaces'), ('decoracao', 'Décoration'), ('reparos', 'Réparations'), ('outro', 'Autre')], max_length=50, verbose_name='Type de service')),
                ('descricao_servico', models.TextField(verbose_name='Description du service')),
                ('area_aproximada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface approximative (m²)')),
                ('urgencia', models.CharField(choices=[('baixa', 'Pas pressé'), ('media', 'Normal'), ('alta', 'Urgent'), ('critica', 'Très urgent')], default='media', max_length=20, verbose_name='Urgence')),
                ('data_inicio_desejada', models.DateField(blank=True, null=True, verbose_name='Date de début souhaitée')),
                ('orcamento_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget maximum (€)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('status', models.CharField(choices=[('pendente', 'En attente'), ('em_elaboracao', "En cours d'élaboration"), ('enviado', 'Envoyé au client'), ('aceito', 'Accepté'), ('recusado', 'Refusé'), ('expirado', 'Expiré')], default='pendente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_orcamento', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_orcamento', to='orcamentos.projeto')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='solicitacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orcamento', to='orcamentos.solicitacaoorcamento'),
        ),
    ]
