# Generated by Django 5.2.6 on 2025-10-13 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField(verbose_name='Date et heure souhaitées')),
                ('tipo', models.CharField(choices=[('visita', 'Visite technique sur site'), ('appel', 'Appel téléphonique'), ('visio', 'Visioconférence')], default='visita', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'En attente'), ('confirmado', 'Confirmé'), ('recusado', 'Refusé'), ('cancelado', 'Annulé')], default='pendente', max_length=12)),
                ('mensagem', models.TextField(blank=True, verbose_name='Message du client')),
                ('resposta_admin', models.TextField(blank=True, verbose_name="Réponse de l'admin")),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_orcamento', to=settings.AUTH_USER_MODEL)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='orcamentos.orcamento')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-created_at'],
            },
        ),
    ]
