# Generated by Django 5.2.6 on 2025-09-28 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[\\+]?[0-9\\s\\-\\(\\)]+$')], verbose_name='Téléphone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='itemorcamento',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Item du devis', 'verbose_name_plural': 'Itens du devis'},
        ),
        migrations.RemoveField(
            model_name='itemorcamento',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='itemorcamento',
            name='total_item',
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='atividade',
            field=models.CharField(choices=[('marchandise', 'Marchandise'), ('service', 'Service')], default='marchandise', max_length=20, verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='preco_compra_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat unitaire"),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='preco_unitario_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='P.U HT'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='preco_unitario_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='P.U TTC'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='remise_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='taxa_tva',
            field=models.CharField(choices=[('20', 'TVA 20%'), ('10', 'TVA 10%'), ('5.5', 'TVA 5,5%'), ('0', 'Exonérée')], default='20', max_length=5, verbose_name='Taxe TVA'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total HT'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total TTC'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='unidade',
            field=models.CharField(choices=[('unite', 'Unité'), ('piece', 'Pièce'), ('m2', 'M²'), ('ml', 'ML'), ('longueur', 'Longueur'), ('kg', 'Kg'), ('heure', 'Heure'), ('forfait', 'Forfait')], default='unite', max_length=20, verbose_name='Unité'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('descricao', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unidade', models.CharField(choices=[('unite', 'Unité'), ('piece', 'Pièce'), ('m2', 'M²'), ('ml', 'ML'), ('longueur', 'Longueur'), ('kg', 'Kg'), ('heure', 'Heure'), ('forfait', 'Forfait')], default='unite', max_length=20, verbose_name="Type d'unité")),
                ('atividade', models.CharField(choices=[('marchandise', 'Marchandise'), ('service', 'Service')], default='marchandise', max_length=20, verbose_name='Activité')),
                ('preco_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Prix d'achat")),
                ('margem_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Marge HT')),
                ('margem_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Marge HT em %')),
                ('preco_venda_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='P.Vente HT')),
                ('taxa_tva', models.CharField(choices=[('20', 'TVA 20%'), ('10', 'TVA 10%'), ('5.5', 'TVA 5,5%'), ('0', 'Exonérée')], default='20', max_length=5, verbose_name='Taxe TVA')),
                ('preco_venda_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='P.Vente TTC')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/', verbose_name='Photo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='orcamentos.fornecedor', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['referencia'],
            },
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamentos.produto', verbose_name='Produto de referência'),
        ),
    ]
