# Generated by Django 5.2.6 on 2025-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_fornecedor_alter_itemorcamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèce'), ('carte_bancaire', 'Carte bancaire')], default='virement', max_length=20, verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='condicoes_pagamento',
            field=models.CharField(choices=[('comptant', 'Comptant'), ('acompte_30', "30% d'acompte, solde à la fin"), ('acompte_50', "50% d'acompte, solde à la fin"), ('echeance_30', 'Paiement à 30 jours'), ('echeance_60', 'Paiement à 60 jours'), ('personnalise', 'Conditions personnalisées')], default='comptant', max_length=20, verbose_name='Conditions de paiement'),
        ),
    ]
