# Generated by Django 5.2.6 on 2025-10-03 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_orcamento_tipo_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Titre de la facture')),
                ('descricao', models.TextField(verbose_name='Description')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sous-total')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant de la remise')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('data_vencimento', models.DateField(verbose_name="Date d'échéance")),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('condicoes_pagamento', models.CharField(choices=[('comptant', 'Comptant'), ('acompte_30', "30% d'acompte, solde à la fin"), ('acompte_50', "50% d'acompte, solde à la fin"), ('echeance_30', 'Paiement à 30 jours'), ('echeance_60', 'Paiement à 60 jours'), ('personnalise', 'Conditions personnalisées')], default='comptant', max_length=20, verbose_name='Conditions de paiement')),
                ('tipo_pagamento', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèce'), ('carte_bancaire', 'Carte bancaire')], default='virement', max_length=20, verbose_name='Type de paiement')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('annulee', 'Annulée'), ('en_retard', 'En retard')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observations')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas_elaboradas', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='orcamentos.orcamento', verbose_name='Devis de référence')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('descricao', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unidade', models.CharField(choices=[('unite', 'Unité'), ('piece', 'Pièce'), ('m2', 'M²'), ('ml', 'ML'), ('longueur', 'Longueur'), ('kg', 'Kg'), ('heure', 'Heure'), ('forfait', 'Forfait')], default='unite', max_length=20, verbose_name='Unité')),
                ('atividade', models.CharField(choices=[('marchandise', 'Marchandise'), ('service', 'Service')], default='marchandise', max_length=20, verbose_name='Activité')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('preco_unitario_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='P.U HT')),
                ('preco_unitario_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='P.U TTC')),
                ('remise_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total HT')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total TTC')),
                ('taxa_tva', models.CharField(choices=[('20', 'TVA 20%'), ('10', 'TVA 10%'), ('5.5', 'TVA 5,5%'), ('0', 'Exonérée')], default='20', max_length=5, verbose_name='Taxe TVA')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.facture')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamentos.produto', verbose_name='Produto de referência')),
            ],
            options={
                'verbose_name': 'Item de la facture',
                'verbose_name_plural': 'Itens de la facture',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
