# Generated by Django 5.2.6 on 2025-10-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_add_auditoria'),
        ('orcamentos', '0005_facture_itemfacture'),
    ]

    operations = [
    ]
