# Generated by Django 5.2.6 on 2025-10-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_merge_0002_add_auditoria_0005_facture_itemfacture'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='orcamentos__timesta_77cd44_idx',
            old_name='orcamentos_l_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='orcamentos__usuario_3c0485_idx',
            old_name='orcamentos_l_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='orcamentos__acao_57c2ff_idx',
            old_name='orcamentos_l_acao_idx',
        ),
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='orcamentos__modulo_a0084b_idx',
            old_name='orcamentos_l_modulo_idx',
        ),
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='orcamentos__content_eab749_idx',
            old_name='orcamentos_l_content_obj_idx',
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Création'), ('edicao', 'Modification'), ('exclusao', 'Suppression'), ('visualizacao', 'Consultation'), ('envio', 'Envoi'), ('aprovacao', 'Approbation'), ('rejeicao', 'Rejet'), ('cancelamento', 'Annulation'), ('download', 'Téléchargement'), ('vinculacao_orfao', 'Liaison demande orpheline'), ('deteccao_orfao', 'Détection demande orpheline'), ('processamento_lote', 'Traitement en lot'), ('notificacao_vinculacao', 'Notification de liaison'), ('criacao_fatura', 'Création de facture'), ('envio_fatura', 'Envoi de facture'), ('pagamento_fatura', 'Paiement de facture'), ('visualizacao_fatura', 'Consultation de facture'), ('download_fatura_pdf', 'Téléchargement PDF facture'), ('edicao_fatura', 'Modification de facture'), ('anulacao_fatura', 'Annulation de facture')], max_length=30, verbose_name='Action'),
        ),
    ]
