# Generated by Django 5.2.6 on 2025-10-08 20:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0007_rename_orcamentos_l_timesta_idx_orcamentos__timesta_77cd44_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('nova_solicitacao', 'Nouvelle demande de devis'), ('orcamento_elaborado', 'Devis élaboré'), ('orcamento_enviado', 'Devis envoyé'), ('orcamento_aceito', 'Devis accepté'), ('orcamento_recusado', 'Devis refusé'), ('projeto_criado', 'Nouveau projet créé'), ('fatura_criada', 'Nouvelle facture créée'), ('fatura_enviada', 'Facture envoyée'), ('fatura_paga', 'Facture payée')], max_length=30),
        ),
        migrations.CreateModel(
            name='AcompteOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('inicial', 'Acompte initial'), ('intermediario', 'Acompte intermédiaire'), ('final', 'Solde final')], default='inicial', max_length=20, verbose_name="Type d'acompte")),
                ('descricao', models.CharField(max_length=255, verbose_name='Description')),
                ('percentual', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Pourcentage (%)')),
                ('valor_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT (€)')),
                ('valor_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC (€)')),
                ('valor_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant TVA (€)')),
                ('data_vencimento', models.DateField(verbose_name="Date d'échéance")),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('pendente', 'En attente'), ('pago', 'Payé'), ('vencido', 'Échu'), ('cancelado', 'Annulé')], default='pendente', max_length=20, verbose_name='Statut')),
                ('tipo_pagamento', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèce'), ('carte_bancaire', 'Carte bancaire')], default='virement', max_length=20, verbose_name='Type de paiement')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acomptes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('fatura_acompte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompte_origem', to='orcamentos.facture', verbose_name="Facture d'acompte")),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomptes', to='orcamentos.orcamento', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Acompte',
                'verbose_name_plural': 'Acomptes',
                'ordering': ['-created_at'],
                'unique_together': {('orcamento', 'numero')},
            },
        ),
    ]
